theme: jekyll-theme-minimal
title: Servisní a provozní historie
description: Model architektury Servisní a provozní historie je praktickou částí diplomové práce _Návrh architektury distribuované databáze pro uchování servisní historie automobilu_ (Martin Friedmann, Vysoká škola ekonomická, 2022).
