remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Servisní a provozní historie
description: Model architektury Servisní a provozní historie je praktickou částí diplomové práce _Návrh architektury distribuované databáze pro uchování servisní historie automobilu_ (Martin Friedmann, Vysoká škola ekonomická, 2022).
